[book]
title = ""
description = "Markdown format php manual"
authors = ["php"]
language = "zh"
multilingual = false
src = "src"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = false
limit-results = 10
teaser-word-count = 30
use-boolean-and = false
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true